# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConvertisseurAgi
                                 A QGIS plugin
 Convertisseur SHP/JSON/GPKG vers AGI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-04
        copyright            : (C) 2025 by D3E Electronique
        email                : emilien.coustillas@d3e.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming

from .Convertisseur_Agi import ConvertisseurAgi

def classFactory(iface):  # pylint: disable=invalid-name
    return ConvertisseurAgi(iface)
